### ISSUE TITLE
Autocompletion works even if there's no match

### ISSUE THREAD

**Issue by kolumb** [tsoding/something#294] opened 2020-11-18 23:24 UTC
### Steps to reproduce
1. Execute some command using autocompletion.
1. Type `f` in empty console input.
1. Press `Ctrl`+`Space`.

### Observed
Your can't type additional characters or delete existing. You can select and apply suggestion from invisible "select popup" with all commands. Or close invisible "select popup" to continue.

### Expected
Completion popup should stay disabled. Maybe give a feedback that there's no such command to autocomplete.

**Comment by rexim** [comment] 2020-11-19 11:27
@kolumb should be fixed by #296. Please check the latest commit when you get a chance and close the issue if the problem is fixed! :+1: Thank you for reporting this!

**Closed** 2020-11-19 12:46 UTC
