### ISSUE TITLE
Bug:  Console::History::up() and ...down() lag one step behind

### ISSUE THREAD

**Issue by JaroslawWiosna** [tsoding/something#333] opened 2020-12-19 22:22 UTC
Reproduced in 88f23024cad76c90614ecb6ddccff469cef1966c

## Steps to reproduce

1. open console
2. issue a couple of commands, like:

```
1
2
3
4
history
```

3. press <kbd>UP</kbd> four times

You should now see `2`, as expected:

![obraz](https://user-images.githubusercontent.com/11769750/102700732-7ef90d00-4250-11eb-818d-fb16c1373e3c.png)

4. press <kbd>DOWN</kbd>:
  - expected behaviour:  You should see `3`, which was issued after `2`
  - observed behaviour: `1`, like <kbd>UP</kbd> was pressed. Then, you have to press <kbd>DOWN</kbd> again to see `3`

**Comment by rexim** [comment] 2020-12-27 13:05
@JaroslawWiosna tried to address the problem in #337. Please check out the latest version when you get a chance and close the issue if the problem is fixed.

**Closed** 2020-12-27 15:35 UTC
