### ISSUE TITLE
SDL flags considerations

### ISSUE THREAD

**Issue by k0-dev** [tsoding/something#3] opened 2020-02-10 14:53 UTC
As the documentation says (https://wiki.libsdl.org/SDL_Init | https://wiki.libsdl.org/SDL_CreateWindow): 

- SDL_INIT_VIDEO automatically initializes the events subsystem
- SDL_WINDOW_SHOWN is ignored by SDL_CreateWindow(). The SDL_Window is implicitly shown if SDL_WINDOW_HIDDEN is not set

So, it should be possible to remove SDL_WINDOW_SHOWN from SDL_CreateWindow() and SDL_INIT_EVENTS from SDL_Init. Not mandatory tho, of course

**Comment by rexim** [comment] 2020-02-10 15:04
@k0-dev cool! Didn't know that! Thank you sharing this information! :+1: Feel free to submit a PR if you want. If not I'll resolve this issue myself on the next gamedev stream.

**Comment by k0-dev** [comment] 2020-02-10 15:15
I am very new to github, I tryied to do a pull request but failed :(
Maybe when i will join your streaming tomorrow you can show me how to do that ahah
Sorry again for submitting an issue instead of a pull request

**Comment by rexim** [comment] 2020-02-10 15:20
@k0-dev no worries! Feel free to join Saturday stream!

P.S. there is no need to close this issue. On GitHub we usually close the issue when the problem described in the issue is actually resolved. Since we have not removed initialization of Event subsystem and SDL_WINDOW_SHOWN flag the problem is not resolved.

**Comment by k0-dev** [comment] 2020-02-10 15:24
Oh I see. By the way if you plan to use SDL_GetWindowFlags(), then you should explicitly use SDL_WINDOW_SHOWN in the window creation, otherwise it will not return that flag

**Closed** 2020-02-15 16:30 UTC
