### ISSUE TITLE
Color of particles don't change after the fall

### ISSUE THREAD

**Issue by kolumb** [tsoding/something#258] opened 2020-11-01 16:37 UTC
### Steps to reproduce
* Jump to other tile type.
* Don't move while on ground.
* Jump.

### Observed
![Particles preserve colors-min](https://user-images.githubusercontent.com/4366033/97808543-3d94aa00-1c70-11eb-8a30-a9841a72110c.gif)
Particles have color of tile where you walked last time.

### Expected
Color of particles is the same as color of tile.

**Comment by rexim** [comment] 2020-11-15 11:16
@kolumb tried to fix that in #282. Please check the latest version when you get a chance and close the issue if the problem is fixed. Thanks for reporting this!

**Closed** 2020-11-15 11:21 UTC
